# Generated by Django 5.2.4 on 2025-07-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveBigIntegerField()),
                ('nivel', models.CharField(choices=[('básico', 'BASICO'), ('intermedio', 'INTERMEDIO'), ('avanzado', 'AVANZADO')], default='básico', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('capacidad', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_de_archivo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'VIDEO'), ('imagen', 'IMAGEN')], default='pdf', max_length=10)),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.taller')),
            ],
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.estudiante')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.taller')),
            ],
        ),
    ]
