# Generated by Django 5.2.4 on 2025-07-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
