# Generated by Django 5.2.4 on 2025-07-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_taller_descripcion_alter_taller_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='capacidad',
            field=models.IntegerField(default=20),
        ),
    ]
