# Generated by Django 5.2.4 on 2025-07-12 22:05

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_taller_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.CharField(default='nombre@gmail.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='capacidad',
            field=models.IntegerField(default=20, validators=[blog.validators.validate_capacity]),
        ),
    ]
