# Generated by Django 5.2.4 on 2025-07-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_estudiante_email_alter_taller_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
